{
 "title": "Pizza dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Requests / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Statistics",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_CPU{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "system_MEM{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth attempts / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(auth_Fail{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(auth_Pass{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "activeUsers_numActiveUsers{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(sales_unitsSold{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(sales_totalRevenue{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sales_creationErrors{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "latency_elapsedTime{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "latency_HQ_delay{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\"}"
    }
   ]
  },
  {
   "title": "Development",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dev HTTP stats",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "rate(request_total{source=\"jwt-pizza-service-dev\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Dev loggs",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "{component=\"jwt-pizza-service-dev\"}"
      }
     ]
    }
   ]
  }
 ]
}